name: Release Extension to Sonatype

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  release:
    uses: mitchresch/build-logic/.github/workflows/extension-release-published.yml@main
    secrets: inherit
